# SPDX-License-Identifier: GPL-2.0
#
#  Makefile for the Linux BSH bus drivers.
#
obj-$(CONFIG_BSHDBUS) += bshdbus_netdev.o
bshdbus_netdev-y += skb.o
bshdbus_netdev-y += netdev.o

obj-$(CONFIG_BSHDBUS) += dbus2/
