# SPDX-License-Identifier: GPL-2.0
#
#  Makefile for the BSH bus network core.
#

obj-$(CONFIG_BSHDBUS) += bshdbus.o
bshdbus-y := af_bshdbus.o

obj-$(CONFIG_BSHDBUS_DBUS2) += bshdbus-dbus2.o
bshdbus-dbus2-y := dbus2.o
